drop table AppUser IF exists;

create table AppUser (
  id bigint generated by Default as identity (start with 1, increment by 1) not NULL,
  username varchar(100) not NULL,
  password varchar(200) not NULL,
  primary key (id),
  CONSTRAINT AppUser_Name_Unique UNIQUE (username)
);